<?php
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$bodyTerms = $this->themeSetting('browse_body_property_terms', [$bodyTerm]);
?>
<?php if (!empty($resources)): ?>
<h3><?php echo $title; ?></h3>
<div class="resource-list">
    <?php
    foreach ($resources as $resource):
        echo $this->partial('common/resource', [
            'resource' => $resource,
            'headingTerm' => $headingTerm,
            'bodyTerms' => $bodyTerms,
        ]);
    endforeach;
    ?>
</div>
<?php endif; ?>
