<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>
<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
// The controller name is used to simplify compatibility with default themes (javascript and css that use default classes).
$resourceName = $resource->getControllerName();
$searchPageId = $this->themeSetting('search_page_id');
$hasBasket = $this->getHelperPluginManager()->has('updateBasketLink');

if ($resourceName === 'item-set') {
    $resourceUrl = $searchPageId
        ? $this->url('search-page-' . $searchPageId, [], ['query' => ['itemSet' => ['ids' => [$resource->id()]]]], true)
        : $this->url('site/resource/id', ['controller' => 'item-set', 'action' => 'show', 'id' => $resource->id()], [], true);
} else {
    $resourceUrl = $resource->url();
}

?>
<div class="<?php echo $resourceName; ?> resource">
    <div class="resource-thumbnail">
        <?php $media = $resource->primaryMedia(); ?>
        <?php if ($media): ?>
            <?php echo $hyperlink->raw(
                $this->thumbnail($media, 'square', ['title' => $media->displayTitle(), 'alt' => $media->mediaType() . ' thumbnail']),
                $resourceUrl
            ); ?>
        <?php endif; ?>
    </div>
    <div class="resource-metadata">
        <h4>
            <?php if ($hasBasket && in_array($resourceName, ['item', 'media'])): ?>
                <?php echo $this->updateBasketLink($resource); ?>
            <?php endif; ?>
            <?php echo $hyperlink($resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]), $resourceUrl); ?>
        </h4>
        <?php if ($resourceName === 'item-set'): ?>
            <div class="items-count">
                <?php echo sprintf($this->translatePlural('%s item', '%s items', $resource->itemCount()), $resource->itemCount()); ?>
            </div>
        <?php endif; ?>

        <?php foreach ($bodyTerms as $term): ?>
            <?php $value = $resource->value($term, ['type' => 'literal']); ?>
            <?php if ($value): ?>
                <div class="<?php echo str_replace(':', '-', $term); ?>">
                    <span><?php echo $value; ?></span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
