<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $sortHeadings
 */

$assetUrl = $this->plugin('assetUrl');
?>
<div class="search-results-header">
    <?php echo $this->sortSelector($sortHeadings, 'common/sort-selector-links'); ?>
    <div>
        <a class="browse-view-type browse-view-type-grid" href="#"><img src="<?= $assetUrl('img/grid.svg') ?>"/></a>
        <a class="browse-view-type browse-view-type-list" href="#"><img src="<?= $assetUrl('img/list.svg') ?>"/></a>
    </div>
</div>
