<div class="search-results-header">
    <?php echo $this->sortSelector($sortHeadings, 'common/sort-selector-links'); ?>
    <div>
        <a class="browse-view-type browse-view-type-grid" href="#"><img src="<?php echo $this->assetUrl('img/grid.svg'); ?>"/></a>
        <a class="browse-view-type browse-view-type-list" href="#"><img src="<?php echo $this->assetUrl('img/list.svg'); ?>"/></a>
    </div>
</div>
