<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
$escape = $this->plugin('escapeHtml');
// The controller name is used to simplify compatibility with default themes (javascript and css that use default classes).
$resourceName = $resource->getControllerName();
$searchPageId = $this->themeSetting('search_page_id');
$hasBasket = $this->getHelperPluginManager()->has('updateBasketLink');

if ($resourceName === 'item-set') {
    $resourceUrl = $searchPageId
        ? $this->url('search-page-' . $searchPageId, [], ['query' => ['itemSet' => ['ids' => [$resource->id()]]]], true)
        : $this->url('site/resource/id', ['controller' => 'item-set', 'action' => 'show', 'id' => $resource->id()], [], true);
} else {
    $resourceUrl = $this->ResourceUrl($resource);
}
?>

<div class="<?php echo $resourceName; ?> resource">
    <div class="resource-thumbnail">
        <?php
            if ($resourceName === 'media') {
                $media = $resource;
            } else {
                $media = $resource->primaryMedia();
            }
        ?>

        <?php if ($media): ?>
            <a href="<?php echo $escape($resourceUrl); ?>">
                <img
                    src="<?php echo $escape($media->thumbnailUrl('square')); ?>"
                    title="<?php echo $escape($media->displayTitle()); ?>"
                    alt="<?php echo $escape($media->mediaType()); ?> thumbnail"
                />
            </a>
        <?php endif; ?>
    </div>
    <div class="resource-metadata">
        <h4>
            <?php if (in_array($resourceName, ['item', 'media']) && $hasBasket): ?>
                <?php echo $this->updateBasketLink($resource); ?>
            <?php endif; ?>
            <a href="<?php echo $escape($resourceUrl); ?>"><?php echo $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]); ?></a>
        </h4>
        <?php if ($resourceName === 'item-set'): ?>
            <div class="items-count">
                <?php echo sprintf($this->translatePlural('%s item', '%s items', $resource->itemCount()), $resource->itemCount()); ?>
            </div>
        <?php endif; ?>

        <?php $value = $resource->value($bodyTerm, ['type' => 'literal']); ?>
        <?php if ($value): ?>
            <div class="<?php echo str_replace(':', '-', $bodyTerm); ?>">
                <span><?php echo $value; ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
