<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set resource browse'); ?>

<?php echo $this->pageTitle($translate('Item sets'), 2); ?>

<?php echo $this->searchFilters(); ?>
<?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
<?php if (!empty($itemSets)): ?>
    <?php $this->trigger('view.browse.before'); ?>
    <div id="collections" <?php /* class="resource-list"*/ ?>>
        <main><?php // TODO Remove <main> from here. ?>
        <?php echo $this->partial('omeka/site/resource/list', [
            'resourceType' => 'item_sets',
            'resources' => $itemSets,
        ]); ?>
        </main>
    </div>
    <?php $this->trigger('view.browse.after'); ?>
    <?php echo $this->pagination('common/pagination-links'); ?>
<?php endif; ?>
