<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery();
if (isset($itemSet)):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$itemSetShow = isset($itemSet);
$this->headLink()->appendStylesheet($this->assetUrl('css/search.css', 'Search'));
$this->headScript()->appendFile($this->assetUrl('js/search.js', 'Search'));
$totalCount = $this->pagination()->getPaginator()->getTotalCount();
$sortHeadings = [
    [
        'label' => $this->translate('Title'),
        'value' => 'dcterms:title',
    ],
    [
        'label' => $this->translate('Date'),
        'value' => 'dcterms:date',
    ],
];
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $this->translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo $this->pageTitle($this->translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($this->translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<?php echo $this->hyperlink($this->translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
<?php $this->trigger('view.browse.before'); ?>

<div class="browse-list-wrapper">
    <div class="browse-list">
        <?php if ($totalCount): ?>
            <?php
                echo $this->partial('common/resource-header', [
                    'sortHeadings' => $sortHeadings,
                ]);
            ?>

            <?php
                echo $this->partial('common/resource-list', [
                    'resources' => $resources,
                    'title' => sprintf($this->translatePlural('%s item', '%s items', $totalCount), $totalCount),
                ]);
            ?>

            <?php
                echo $this->partial('common/resource-footer', [
                    'resources' => $resources,
                ]);
            ?>
        <?php else: ?>
            <div class="noresults"><?php echo $this->translate('No items.'); ?></div>
        <?php endif; ?>
    </div>
</div>

<?php $this->trigger('view.browse.after'); ?>

<?php if ($itemSetShow): ?>
</div>
<?php endif; ?>
