<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();
// UniversalViewer can't display html, so when there is an html media, use
// default render for all files.
$hasHtmlMedia = false;
foreach ($itemMedia as $media):
    if ($media->renderer() === 'html'):
        $hasHtmlMedia = true;
        break;
    endif;
endforeach;
?>

<div id="content" role="navigation">
    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    <?php $this->trigger('view.show.before'); ?>

    <?php if ($itemMedia): ?>
    <div class="psl_uv">
        <?php if (!$hasHtmlMedia && $this->getHelperPluginManager()->has('universalViewer')): ?>
            <?php echo $this->universalViewer($item); ?>
        <?php else: ?>
            <div class="media-embeds">
            <?php
            foreach ($itemMedia as $media):
                echo $media->render();
            endforeach;
            ?>
            </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="resource-metadata-wrapper">
        <div class="resource-metadata">
            <?php echo $item->displayValues(['viewName' => 'psl/resource-values']); ?>
        </div>
    </div>

    <div class="media-list-wrapper">
        <div class="media-list">
            <?php foreach ($itemMedia as $media): ?>
                <a href="<?php echo $media->url(); ?>" class="media resource">
                    <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>" title="<?php echo $escape($media->displayTitle()); ?>">
                </a>
            <?php endforeach; ?>
        </div>
    </div>

    <?php echo $this->partial('psl/toolbox', [
        'resource' => $item,
    ]); ?>

    <?php $this->trigger('view.show.after'); ?>
</div>
