<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();
?>

<div id="content" role="navigation">
    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>

    <?php if ($itemMedia): ?>
    <div class="psl_uv">
        <?php if ($this->getHelperPluginManager()->has('universalViewer')): ?>
            <?php echo $this->universalViewer($item); ?>
        <?php else: ?>
            <div class="media-embeds">
            <?php
            foreach ($itemMedia as $media):
                echo $media->render();
            endforeach;
            ?>
            </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="resource-metadata-wrapper">
        <div class="resource-metadata">
            <?php echo $item->displayValues(['viewName' => 'psl/resource-values']); ?>
        </div>
    </div>

    <div class="media-list-wrapper">
        <div class="media-list">
            <?php foreach ($itemMedia as $media): ?>
                <a href="<?php echo $media->url(); ?>" class="media resource">
                    <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>" title="<?php echo $escape($media->displayTitle()); ?>">
                </a>
            <?php endforeach; ?>
        </div>
    </div>

    <?php echo $this->partial('psl/toolbox', [
        'resource' => $item,
    ]); ?>
</div>

<script>
    $(document).ready(function() {
        var mediaList = $('div.media-list');
        if (mediaList.length) {
            $('<a>')
                .addClass('media-list-toggle')
                .html(<?php echo json_encode($this->translate('Access to files')); ?>)
                .on('click', function(e) {
                    e.preventDefault();
                    if (mediaList.is(':visible')) {
                        mediaList.hide();
                        $(this).removeClass('media-list-visible');
                        $(this).addClass('media-list-hidden');
                    } else {
                        mediaList.show();
                        $(this).removeClass('media-list-hidden');
                        $(this).addClass('media-list-visible');
                    }
                })
                .insertBefore(mediaList)
                .trigger('click');
        }
    });
</script>
