<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item resource show'); ?>

<div id="content" role="navigation">
    <?php echo $this->SearchForm(); ?>

    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>

    <?php echo $this->universalViewer($item); ?>

    <?php if ($item->media()): ?>
        <div class="media-list">
            <?php foreach ($item->media() as $media): ?>
                <a href="<?php echo $media->url(); ?>" class="media resource">
                    <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>" title="<?php echo $escape($media->displayTitle()); ?>">
                </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <div class="resource-metadata-wrapper">
        <div class="resource-metadata">
            <h2><?php echo $this->translate('Metadata'); ?></h2>
            <?php echo $item->displayValues(['viewName' => 'psl/resource-values']); ?>
        </div>
    </div>

    <?php echo $this->partial('psl/toolbox', [
        'resource' => $item,
    ]); ?>
</div>
