<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>
<?php $pageTitle = $media->item()->displayTitle() . ' : ' . $media->displayTitle(); ?>
<?php echo $this->pageTitle($pageTitle, 2); ?>
<?php $this->trigger('view.show.before'); ?>
<?php echo $media->render(); ?>
<?php if (!empty($media->values())): ?>
    <div class="resource-metadata-wrapper">
        <div class="resource-metadata">
            <h2><?php echo $translate('Metadata'); ?></h2>
            <?php echo $media->displayValues(['viewName' => 'psl/resource-values']); ?>
        </div>
    </div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>
<?php echo $this->partial('psl/toolbox', [
    'resource' => $media,
]); ?>
