<div id="content" role="main">
    <div id="search-form-wrapper">
        <div id="search-form">
            <?php echo $this->SearchForm(); ?>
        </div>
    </div>

    <?php
        $itemSets = $this->api()->search('item_sets', [
            'is_public' => 1,
            'limit' => 8,
            'sort_by' => 'created',
            'sort_order' => 'desc',
        ])->getContent();
    ?>
    <?php if (!empty($itemSets)): ?>
        <div id="collections">
            <header>
                <h2>Collections</h2>
                <?php $collectionsUrl = $this->url('site/resource', [
                    'controller' => 'item-set',
                    'action' => 'browse',
                ], true); ?>
                <div class="ruler"></div>
                <a href="<?php echo $collectionsUrl; ?>"><img src="/themes/psl/asset/images/bullet.svg"/> Toutes les collections</a>
            </header>
            <main>
                <?php echo $this->partial('psl/item-sets', [
                    'itemSets' => $itemSets,
                ]); ?>
            </main>
        </div>
    <?php endif; ?>
</div>
