<?php
    $itemSets = $this->api()->search('item_sets')->getContent();
?>
<div id="content" role="main">
    <h2><?php echo $this->translate('Browse'); ?></h2>
    <a href="<?php echo $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], true); ?>"><?php echo $this->translate('Browse all items'); ?></a>

    <?php if (!empty($itemSets)): ?>
        <h2>Item sets</h2>
        <ul>
            <?php foreach ($itemSets as $itemSet): ?>
                <li><a href="<?php echo $this->cleanUrl($itemSet); ?>"><?php echo $itemSet->displayTitle(); ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>
