<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var string $resourceType
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var string $heading
 * @var string $linkText
 * @var array $query
 */

// Copy of view/omeka/site/index/index.phtml, but adapted to allow multiple blocks.

$translate = $this->plugin('translate');

// Avoid to set multiple front images in case of multiple Browse preview".
global $firstBlockForHome;
if (!$firstBlockForHome):
$firstBlockForHome = true;

// The search form needs to be wrapped on home page, so quick set a variable to
// check it in layout. This is simpler than a check of the home page url or route.
$this->getHelperPluginManager()->get('view_model')->getRoot()->setVariable('isHomePage', true);
$this->htmlElement('body')->appendAttribute('class', 'home');

$frontPageImages = [];
for ($i = 1; $i < 11; $i++) {
    $frontPageImage = $this->themeSettingAssetUrl("front_page_image_$i");
    if ($frontPageImage) {
        $frontPageImages[] = $frontPageImage;
    }
}

if (count($frontPageImages)) {
    $index = rand(0, count($frontPageImages) - 1);
    $url = $frontPageImages[$index];
    $this->headStyle()->appendStyle('
        #search-form-wrapper {
            background-image: url("' . $url . '");
        }
    ');
}

endif;

if (count($resources)):

?>
<div class="preview-block">
    <header>
        <?php if ($heading): ?>
        <h2><?php echo $translate($heading); ?></h2>
        <?php endif; ?>
        <div class="ruler"></div>
        <?php
            if ($linkText):
                // Check if module Search is enabled.
                $searchMainPage = in_array($resourceType, ['item', 'item-set']) && $this->siteSetting('search_main_page');
                if ($searchMainPage):
                    $resourceTypes = ['item-set' => 'item_sets', 'item' => 'items', 'media' => 'media'];
                    $query['resource_type'] = $resourceTypes[$resourceType];
                    $url = $this->url('search-page-' . $searchMainPage, ['site-slug' => $this->params()->fromRoute('site-slug')], ['query' => $query], true);
                else:
                    $url = $this->url('site/resource', ['controller' => $resourceType, 'action' => 'browse', 'site-slug' => $this->params()->fromRoute('site-slug')], ['query' => $query], true);
                endif;
            ?>
        <a href="<?php echo $url; ?>">
            <img src="<?php echo $this->assetUrl('img/bullet.svg'); ?>"/>
            <?php echo $translate($linkText); ?>
        </a>
        <?php
            endif;
        ?>
    </header>
    <main><?php // TODO Remove <main> from here. ?>
        <?php echo $this->partial('omeka/site/resource/list', [
            'resourceType' => $resourceType,
            'resources' => $resources,
        ]); ?>
    </main>
</div>

<?php endif; ?>
