<?php
$translate = $this->plugin('translate');
?>
<?php if (empty($itemSets)): ?>
<p><?php echo $this->translate('There is no item sets for this site.'); ?></p>
<?php else: ?>
<?php foreach ($itemSets as $itemSet): ?>
    <?php
        $itemSetTitle = $itemSet->value('dcterms:alternative', ['type' => 'literal']);
        if (!isset($itemSetTitle)) {
            $itemSetTitle = $itemSet->displayTitle();
        }
    ?>
    <div class="item-set resource collection">
        <?php
        $searchPageId = $this->themeSetting('search_page_id');
        $url = $searchPageId
            ? $this->url('search-page-' . $searchPageId, [], ['query' => ['itemSet' => ['ids' => [$itemSet->id()]]]], true)
            : $this->url('site/resource-id', ['controller' => 'item-set', 'action' => 'show', 'id' => $itemSet->id()], [], true);
        $media = $itemSet->primaryMedia();
        ?>
        <a <?php if ($media): ?>style="background-image: url(<?php echo $media->thumbnailUrl('large'); ?>)"<?php endif; ?> href="<?php echo $url; ?>">
            <div class="collection-title">
                <div>
                    <span><?php echo $itemSetTitle; ?></span>
                </div>
            </div>
            <?php /* if ($description = $itemSet->displayDescription()): ?>
            <div class="description"><?php echo $description; ?></div>
            <?php endif; */ ?>
        </a>
    </div>
<?php endforeach; ?>
<?php endif; ?>
