<?php $ark = $this->getHelperPluginManager()->has('ark') ? $this->ark($resource)->getAbsoluteUrl(): null; ?>
<?php $isMedia = $resource->resourceName() === 'media'; ?>

<div id="psl-toolbox">
    <ul>
        <li class="basket"><?php echo $this->updateBasketLink($resource); ?></li>
        <?php if ($ark): ?>
        <li class="share">
            <a href="#psl-toolbox-share"></a>
        </li>
        <?php endif; ?>
        <?php if ($isMedia): ?>
            <li class="download">
                <a href="#psl-toolbox-download"></a>
            </li>
        <?php endif; ?>
    </ul>
    <?php if ($ark): ?>
    <div id="psl-toolbox-share">
        <label><?php echo $this->translate('Permalink'); ?></label>
        <a href="<?php echo $ark; ?>"><?php echo $ark; ?></a>
    </div>
    <?php endif; ?>
    <?php if ($isMedia): ?>
        <div id="psl-toolbox-download">
            <label><?php echo $this->translate('Original file:'); ?></label>
            <a href="<?php echo $resource->originalUrl(); ?>"><?php echo $resource->filename(); ?></a>
        </div>
    <?php endif; ?>
</div>
<?php $this->headScript()->appendFile($this->assetUrl('js/toolbox.js')); ?>
