<?php
$this->htmlElement('html')->setAttribute('lang', 'en');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/fonts.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/jquery.js', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <header>
            <?php echo $this->themeSetting('header_html'); ?>
<div class="show_basket">

          <?php echo $this->showBasketLink("<img src=\"".$this->assetUrl('images/add_basket.png').'"/>'.$this->translate('BASKET')); ?>
</div>
        </header>

        <main>
            <?php echo $this->content; ?>
        </main>

        <footer>
            <?php echo $this->themeSetting('footer_html'); ?>
        </footer>
    </body>
</html>
